-- Seed exercise library
INSERT INTO exercises (name, muscle_groups, movement_pattern, equipment, is_compound) VALUES
-- Compounds
('Barbell Back Squat', ARRAY['quads','glutes','hamstrings','core'], 'squat', 'barbell', true),
('Barbell Front Squat', ARRAY['quads','glutes','core'], 'squat', 'barbell', true),
('Barbell Deadlift', ARRAY['hamstrings','glutes','back','traps'], 'hinge', 'barbell', true),
('Romanian Deadlift', ARRAY['hamstrings','glutes','lower_back'], 'hinge', 'barbell', true),
('Barbell Bench Press', ARRAY['chest','triceps','anterior_deltoid'], 'push', 'barbell', true),
('Incline Barbell Bench Press', ARRAY['upper_chest','triceps','anterior_deltoid'], 'push', 'barbell', true),
('Barbell Overhead Press', ARRAY['deltoids','triceps','upper_chest'], 'push', 'barbell', true),
('Barbell Row', ARRAY['back','biceps','rear_deltoid'], 'pull', 'barbell', true),
('Pull-Up', ARRAY['lats','biceps','rear_deltoid'], 'pull', 'bodyweight', true),
('Chin-Up', ARRAY['lats','biceps'], 'pull', 'bodyweight', true),
('Dip', ARRAY['chest','triceps','anterior_deltoid'], 'push', 'bodyweight', true),
('Hip Thrust', ARRAY['glutes','hamstrings'], 'hinge', 'barbell', true),
('Leg Press', ARRAY['quads','glutes'], 'squat', 'machine', true),
('Hack Squat', ARRAY['quads','glutes'], 'squat', 'machine', true),
-- Isolation
('Dumbbell Curl', ARRAY['biceps'], 'pull', 'dumbbell', false),
('Barbell Curl', ARRAY['biceps'], 'pull', 'barbell', false),
('Tricep Pushdown', ARRAY['triceps'], 'push', 'cable', false),
('Skull Crusher', ARRAY['triceps'], 'push', 'barbell', false),
('Lateral Raise', ARRAY['lateral_deltoid'], 'other', 'dumbbell', false),
('Face Pull', ARRAY['rear_deltoid','traps'], 'pull', 'cable', false),
('Leg Extension', ARRAY['quads'], 'other', 'machine', false),
('Leg Curl', ARRAY['hamstrings'], 'hinge', 'machine', false),
('Calf Raise', ARRAY['calves'], 'other', 'machine', false),
('Cable Fly', ARRAY['chest'], 'push', 'cable', false),
('Dumbbell Row', ARRAY['back','biceps'], 'pull', 'dumbbell', false),
('Seated Row', ARRAY['back','biceps'], 'pull', 'cable', false),
('Lat Pulldown', ARRAY['lats','biceps'], 'pull', 'cable', false),
('Incline Dumbbell Press', ARRAY['upper_chest','triceps'], 'push', 'dumbbell', false),
('Dumbbell Shoulder Press', ARRAY['deltoids','triceps'], 'push', 'dumbbell', false),
('Ab Wheel Rollout', ARRAY['core'], 'core', 'bodyweight', false),
('Plank', ARRAY['core'], 'core', 'bodyweight', false),
('Cable Crunch', ARRAY['core'], 'core', 'cable', false),
('Nordic Curl', ARRAY['hamstrings'], 'hinge', 'bodyweight', false),
('Bulgarian Split Squat', ARRAY['quads','glutes'], 'squat', 'dumbbell', true),
('Step Up', ARRAY['quads','glutes'], 'squat', 'dumbbell', false),
('Good Morning', ARRAY['hamstrings','lower_back'], 'hinge', 'barbell', false),
('Pendlay Row', ARRAY['back','biceps'], 'pull', 'barbell', true),
('T-Bar Row', ARRAY['back','biceps'], 'pull', 'barbell', true),
('Rack Pull', ARRAY['back','traps','hamstrings'], 'hinge', 'barbell', true),
('Trap Bar Deadlift', ARRAY['quads','hamstrings','glutes','back'], 'hinge', 'trap_bar', true);
